name: doc-grader
channels:
  - conda-forge
dependencies:
  - charset-normalizer
  - ipykernel
  - jupyter
  - langdetect
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pydantic
  - python=3.14
  - python-dotenv
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - stanza
  - streamlit
  - pip:
    - docling
    - language-tool-python
    - marko
    - openai
    - sentence-transformers
    - streamlit-pdf-viewer