"""Shared domain constants for IPP assessment scripts."""

# All known IPP grading codes (both legacy and current).
IPP_CODES: set[str] = {
    "AUTHOR",
    "BADDP",
    "BADUML",
    "BLOK",
    "BW",
    "CH",
    "COMMENT",
    "CONTENT",
    "COPY",
    "DECOMPOSE",
    "DOCTYPE",
    "DP",
    "EX",
    "EXT",
    "FILO",
    "FORM",
    "FORMAT",
    "HOV",
    "HOW",
    "ICH",
    "IR",
    "JAK",
    "KAPTXT",
    "LANG",
    "MDLINES",
    "MEZ",
    "MISSING",
    "NOOP",
    "NOSRP",
    "NOUML",
    "NV",
    "NVI",
    "NVP",
    "NVPDOC",
    "OK",
    "OOP",
    "OWNDIF",
    "PRED",
    "PSR1",
    "PSR12",
    "SAZBA",
    "SHORT",
    "SINGLETON",
    "SPACETAB",
    "SRCFORMAT",
    "STN0",
    "STN1",
    "STN2",
    "STN3",
    "STN4",
    "STN5",
    "STN6",
    "STN9",
    "STRUCT",
    "STYLE",
    "TERM",
    "UML",
    "WHY",
}

# IPP Codes that relate directly to documentation (subset of IPP_CODES).
DOC_CODES: set[str] = {
    "BADDP",
    "BADUML",
    "BLOK",
    "BW",
    "CH",
    "CONTENT",
    "COPY",
    "DOCTYPE",
    "DP",
    "EX",
    "EXT",
    "FILO",
    "FORM",
    "FORMAT",
    "HOV",
    "HOW",
    "ICH",
    "IR",
    "JAK",
    "KAPTXT",
    "LANG",
    "MDLINES",
    "MEZ",
    "MISSING",
    "NOUML",
    "NV",
    "NVPDOC",
    "OK",
    "OOP",
    "OWNDIF",
    "PRED",
    "SAZBA",
    "SHORT",
    "SINGLETON",
    "SPACETAB",
    "STRUCT",
    "STYLE",
    "TERM",
    "UML",
    "WHY",
}

# Bonus codes awarded by human graders (positive impact) that the tool never emits.
BONUS_CODES: frozenset[str] = frozenset({"DP", "EX", "NV", "OK", "OOP"})

# Maps non-canonical spelling variants to their canonical uppercase form.
CODE_ALIASES: dict[str, str] = {
    "PŘED": "PRED",
    "BLOCK": "BLOK",
    "STYL": "STYLE",
    "SYLE": "STYLE",
    "STRUKT.": "STRUCT",
    "TYP.": "TYP",
    "GRAM.": "GRAM",
    "NOOOP": "NOOP",
    "COMMENTS": "COMMENT",
    "OO": "OOP",
    "TERM.": "TERM",
    "NVI": "NV",
}

# Maps normalised legacy DOC_CODES to their canonical rulebook equivalents.
# Bonus codes are omitted.
LEGACY_TO_CANONICAL: dict[str, str] = {
    "BLOK": "SAZBA",
    "DOCTYPE": "SAZBA",
    "FORM": "SAZBA",
    "FORMAT": "SAZBA",
    "HOW": "HOV",
    "MDLINES": "SAZBA",
    "MEZ": "SAZBA",
    "MISSING": "STRUCT",
    "NVPDOC": "BADDP",
    "PRED": "SAZBA",
    "SINGLETON": "BADDP",
    "SPACETAB": "SAZBA",
    "UML": "NOUML",
    "WHY": "JAK",
}

# Maximum documentation points per (year, task_variant), in milibody (mb).
# 100 mb = 1 b
MAX_DOC_POINTS: dict[tuple[str, str], int] = {
    ("2013", "php"): 200,
    ("2013", "py"): 200,
    ("2014", "php"): 200,
    ("2014", "py"): 200,
    ("2015", "php"): 200,
    ("2015", "py"): 200,
    ("2016", "php"): 200,
    ("2016", "py"): 200,
    ("2017", "int"): 300,
    ("2018", "par"): 100,
    ("2018", "int"): 200,
    ("2019", "par"): 100,
    ("2019", "int"): 200,
    ("2020", "par"): 100,
    ("2020", "int"): 200,
    ("2021", "par"): 100,
    ("2021", "int"): 200,
    ("2022", "par"): 100,
    ("2022", "int"): 300,
    ("2023", "par"): 100,
    ("2023", "int"): 400,
    ("2024", "par"): 100,
    ("2024", "int"): 400,
}
